const collectionGroups={birthdays:['birthdays'],events:['geo','wime','tourism'],social:['diamond','diggeo','earth','glossed','church'],print:['brochure','flyers','achievements']};
const fullRail=document.getElementById('complete-rail');
function renderCollection(category){fullRail.querySelectorAll('video').forEach(v=>v.pause());fullRail.replaceChildren();let count=0;
 if(collectionGroups[category]){collectionGroups[category].forEach(key=>{const pr=projects[key];pr.sections.forEach(group=>group.images.forEach((id,i)=>{const card=document.createElement('article');card.className='collection-slide';const btn=document.createElement('button');btn.className='collection-slide-image';btn.dataset.project=key;btn.dataset.creation='';btn.setAttribute('aria-label',`View ${pr.title}, ${group.title}, design ${i+1}`);const img=document.createElement('img');img.src=`assets/${id}.webp`;img.alt=`${pr.title} — ${group.title}, design ${i+1}`;img.loading='lazy';btn.append(img);const caption=document.createElement('div');caption.className='roll-caption';const title=document.createElement('h4');title.textContent=pr.title;const info=document.createElement('p');info.textContent=`${group.title} / ${String(i+1).padStart(2,'0')}`;caption.append(title,info);card.append(btn,caption);fullRail.append(card);count++}))})}
 else if(category==='film'){const card=document.createElement('article');card.className='collection-slide film-slide';const video=document.createElement('video');video.controls=true;video.playsInline=true;video.preload='none';video.poster='assets/collections/edijay.jpg';video.src='assets/collections/edijay.mp4';video.setAttribute('aria-label','Edijay Mega Foodstore AI-generated advertisement');const caption=document.createElement('div');caption.className='roll-caption';caption.innerHTML='<h4>Edijay Mega Foodstore</h4><p>AI-generated advertisement / 00:15</p>';card.append(video,caption);fullRail.append(card);count=1}
 else{['Whitepaper · Platform overview','Scope of business','Privacy policy','Terms and conditions','Disclaimer'].forEach((title,i)=>{const card=document.createElement('a');card.className='document-slide';card.href=`assets/collections/transactx-${i+1}.pdf`;card.target='_blank';card.rel='noopener';const number=document.createElement('span');number.textContent=`TRANSACTX / 0${i+1}`;const heading=document.createElement('h4');heading.textContent=title;const label=document.createElement('span');label.textContent='Read document · PDF';card.append(number,heading,label);fullRail.append(card);count++})}
 document.querySelectorAll('[data-collection]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.collection===category)));document.getElementById('collection-status').textContent=`${count} ${category==='film'?'film':category==='writing'?'documents':'designs'} · Swipe or use the controls`;fullRail.scrollLeft=0;requestAnimationFrame(paintProgress);
}
document.querySelectorAll('[data-collection]').forEach(button=>button.addEventListener('click',()=>renderCollection(button.dataset.collection)));renderCollection('birthdays');
document.querySelectorAll('[data-rail]').forEach(button=>button.addEventListener('click',()=>{const rail=document.getElementById(button.dataset.rail);rail.scrollBy({left:Number(button.dataset.direction)*rail.clientWidth*.85,behavior:document.documentElement.classList.contains('motion-off')?'auto':'smooth'})}));

// One persistent accessibility panel controls all motion and text preferences.
const root=document.documentElement;const accessToggle=document.getElementById('accessibility-toggle');const accessPanel=document.getElementById('accessibility-panel');
const motionControl=document.getElementById('motion-setting');const textControl=document.getElementById('text-setting');const contrastControl=document.getElementById('contrast-setting');
let prefs={motion:!motionPreference.matches,largeText:false,contrast:false};try{const saved=JSON.parse(localStorage.getItem('ellas-accessibility')||'null');if(saved)prefs={...prefs,...saved}}catch{}
function applyPreferences(){root.classList.toggle('motion-off',!prefs.motion);root.classList.toggle('large-text',prefs.largeText);root.classList.toggle('high-contrast',prefs.contrast);motionControl.checked=prefs.motion;textControl.checked=prefs.largeText;contrastControl.checked=prefs.contrast;paused=!prefs.motion;scheduleRotation();try{localStorage.setItem('ellas-accessibility',JSON.stringify(prefs))}catch{}requestAnimationFrame(paintProgress)}
applyPreferences();motionControl.addEventListener('change',()=>{prefs.motion=motionControl.checked;applyPreferences()});textControl.addEventListener('change',()=>{prefs.largeText=textControl.checked;applyPreferences()});contrastControl.addEventListener('change',()=>{prefs.contrast=contrastControl.checked;applyPreferences()});motionPreference.addEventListener('change',e=>{if(e.matches){prefs.motion=false;applyPreferences()}});
function toggleAccess(open){accessPanel.hidden=!open;accessToggle.setAttribute('aria-expanded',String(open));if(open)document.getElementById('accessibility-close').focus();else accessToggle.focus()}
accessToggle.addEventListener('click',()=>toggleAccess(accessPanel.hidden));document.getElementById('accessibility-close').addEventListener('click',()=>toggleAccess(false));accessPanel.addEventListener('keydown',e=>{if(e.key==='Escape')toggleAccess(false)});
const readButton=document.getElementById('read-page');const stopButton=document.getElementById('stop-reading');const readStatus=document.getElementById('reading-status');let readingChunks=[],readingIndex=0,readingSession=0;
function stopReading(){readingSession++;if('speechSynthesis'in window)speechSynthesis.cancel();stopButton.hidden=true;readButton.disabled=false;readingChunks=[]}
if(!('speechSynthesis'in window)){readButton.disabled=true;readStatus.textContent='Read-aloud is unavailable in this browser. Keyboard and screen-reader navigation remain supported.'}
else{readButton.addEventListener('click',()=>{stopReading();const session=readingSession;const main=document.querySelector('main');const parts=[...main.querySelectorAll('h1,h2,h3,h4,p,summary,legend')].filter(el=>el.getClientRects().length&&!el.closest('[aria-hidden="true"]')).map(el=>el.textContent.trim()).filter(Boolean);readingChunks=parts.flatMap(part=>part.match(/[^.!?]+[.!?]*/g)||[part]);readingIndex=0;readButton.disabled=true;stopButton.hidden=false;readStatus.textContent='Reading the page aloud. Use Stop reading at any time.';function speakNext(){if(session!==readingSession)return;if(readingIndex>=readingChunks.length){stopReading();readStatus.textContent='Reading complete.';return}const utterance=new SpeechSynthesisUtterance(readingChunks[readingIndex++]);utterance.lang='en-GB';utterance.rate=.95;utterance.onend=speakNext;utterance.onerror=()=>{if(session===readingSession){stopReading();readStatus.textContent='The browser could not continue reading. You can try again.'}};speechSynthesis.speak(utterance)}speakNext()});stopButton.addEventListener('click',()=>{stopReading();readStatus.textContent='Reading stopped.'});window.addEventListener('pagehide',stopReading)}
