const dialog=document.getElementById('project-dialog');let opener;
function openProject(key,button,creation=false){const project=projects[key];if(!project)return;opener=button;dialog.classList.toggle('certificates-dialog',key==='certificates');document.getElementById('dialog-title').textContent=project.title;document.getElementById('dialog-category').textContent=project.category;document.getElementById('dialog-description').textContent=project.description;document.getElementById('dialog-images').replaceChildren(...project.sections.map(section=>{const group=document.createElement('section');group.className='project-group';const title=document.createElement('h3');title.textContent=section.title;group.append(title);const grid=document.createElement('div');grid.className='project-group-images';section.images.forEach((id,i)=>{const img=document.createElement('img');img.src=`assets/${id}.webp`;img.alt=`${project.title} — ${section.title}, design ${i+1}`;img.loading='lazy';const link=document.createElement('a');link.href=img.src;link.target='_blank';link.rel='noopener';link.setAttribute('aria-label',`Open ${project.title} design ${i+1} at full size`);if(key==='certificates'&&i===0)link.className='certificate-rotate';link.append(img);grid.append(link)});group.append(grid);return group}));window.configureProjectStory?.(key,creation);dialog.showModal();dialog.scrollTop=0;document.body.style.overflow='hidden'}
document.addEventListener('click',event=>{const button=event.target.closest('[data-project]');if(button)openProject(button.dataset.project,button,button.hasAttribute('data-creation'))});
document.getElementById('close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog){const rect=dialog.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)dialog.close()}});dialog.addEventListener('close',()=>{document.body.style.overflow='';opener?.focus({preventScroll:true})});document.getElementById('year').textContent=new Date().getFullYear();
// Featured projects rotate in a fixed frame, with accessible playback controls.
const feature=document.querySelector('.hero-feature');
const featureButton=feature.querySelector('[data-project]');
const featureImage=featureButton.querySelector('img');
const featureTitle=feature.querySelector('figcaption span:last-child');
const slides=[{key:'wime',image:'16',alt:'WIME Awards 2026 welcome design: Give Purpose, Gain Impact'},{key:'geo',image:'03',alt:'Geosciences Week campaign poster in green, white and yellow'},{key:'tourism',image:'09',alt:'Virtual Tourism in Nigeria discussion poster with featured speakers'}];
const motionPreference=matchMedia('(prefers-reduced-motion: reduce)');
let slideIndex=0,paused=motionPreference.matches,rotationTimer;
feature.setAttribute('role','region');feature.setAttribute('aria-label','Featured projects');feature.setAttribute('aria-roledescription','carousel');
const controls=document.createElement('div');controls.className='feature-controls';
const selectors=slides.map((slide,index)=>{const button=document.createElement('button');button.type='button';button.className='feature-selector';button.textContent=String(index+1).padStart(2,'0');button.setAttribute('aria-label',`Show ${projects[slide.key].title}`);button.setAttribute('aria-pressed',String(index===0));button.addEventListener('click',()=>{showSlide(index);scheduleRotation()});controls.append(button);return button});
const playback=document.createElement('button');playback.type='button';playback.className='feature-playback';playback.hidden=true;feature.append(controls);
function updatePlayback(){playback.textContent=paused?'Play':'Pause';playback.setAttribute('aria-label',paused?'Play featured project slideshow':'Pause featured project slideshow')}
function showSlide(index){slideIndex=index;const slide=slides[index];featureButton.dataset.project=slide.key;featureButton.setAttribute('aria-label',`Explore ${projects[slide.key].title}`);featureImage.src=`assets/${slide.image}.webp`;featureImage.alt=slide.alt;featureTitle.textContent=projects[slide.key].title;selectors.forEach((button,i)=>button.setAttribute('aria-pressed',String(i===index)));if(!motionPreference.matches&&!document.documentElement.classList.contains('motion-off')){featureImage.getAnimations().forEach(animation=>animation.cancel());featureImage.animate([{opacity:.25},{opacity:1}],{duration:550,easing:'ease-out'})}}
function scheduleRotation(){clearTimeout(rotationTimer);if(paused||document.documentElement.classList.contains('motion-off')||document.hidden||dialog.open||feature.matches(':hover')||feature.contains(document.activeElement))return;rotationTimer=setTimeout(()=>{showSlide((slideIndex+1)%slides.length);scheduleRotation()},4500)}
playback.addEventListener('click',()=>{paused=!paused;updatePlayback();scheduleRotation()});
feature.addEventListener('mouseenter',()=>clearTimeout(rotationTimer));feature.addEventListener('mouseleave',scheduleRotation);feature.addEventListener('focusin',()=>clearTimeout(rotationTimer));feature.addEventListener('focusout',()=>setTimeout(scheduleRotation,0));document.addEventListener('visibilitychange',scheduleRotation);dialog.addEventListener('close',scheduleRotation);featureButton.addEventListener('click',()=>clearTimeout(rotationTimer));motionPreference.addEventListener('change',event=>{if(event.matches){paused=true;updatePlayback();scheduleRotation()}});
slides.slice(1).forEach(slide=>{const image=new Image();image.src=`assets/${slide.image}.webp`});updatePlayback();scheduleRotation();
